version: '2'
services:
  wmfw_devtools_jsdoc:
    build: .
    volumes:
      # jsdocの設定ファイル
      - ./.jsdoc.json:/root/.jsdoc.json
      # jsdocのREADMEファイル
      - ./README.md:/root/README.md
      # ビルドされたファイルの格納ディレクトリ
      #- ../../dist/docs:/root/build
      # github pagesのディレクトリ
      - ../../../../../docs/dist/wmfw/api/minami:/root/build/api/minami
      # apiドキュメントを作成したいソースファイルの格納ディレクトリ
      - ../../myproject/src:/root/src
