version: "3"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mssql:
    driver: ${VOLUMES_DRIVER}

services:
  ### MSSQL ################################################
  mssql:
    build:
      context: ./mssql
    environment:
      - MSSQL_PID=Express
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ${DATA_PATH_HOST}/mssql:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend

