version: '3'
services:
  # デプロイツール
  gcloud:
    build: ./gcloud
    env_file: .env
    volumes:
      - ../scripts:/scripts
      - ../data:/data
      - ../response:/response
      - ../base64:/base64
      - ../mp3:/mp3
