version: "3.8"
services:
  cdk:
    build: ./cdk
    volumes:
      - ../projects:/app/projects
    env_file: .env
  project-cdk:
    build: ./project-cdk
    volumes:
      - ../projects/cdk:/app
      - /app/node_modules
    command:
      [ npm, run, watch]
