version: '3'
services:
  # プロキシサーバー
  # http://192.168.50.10/ -> http://server/
  # http://192.168.50.10/tests -> http://jasmine/tests/
  proxy:
    build: ./server/proxy
    volumes:
      - ./server/proxy/conf.d:/etc/nginx/conf.d:ro  
    ports:
      -  80:80
    command: [nginx-debug, '-g', 'daemon off;']

  # webサーバー
  nginx:
    image: nginx
    volumes:
      - ../public/index.html:/usr/share/nginx/html/index.html
      - ../dist/bundle-webpack:/usr/share/nginx/html/js:ro

  # 単体テストサーバーの起動
  jasmine:
    build: ./tools/jasmine
    volumes:
      - ../tests/unit/public:/home/workdir/public
      - ../src/browser:/home/workdir/src/spec
      - ../dist/bundle-webpack:/home/workdir/src/js
      - ./tools/jasmine/app.js:/home/workdir/app.js
    working_dir: /home/workdir
    command: node app.js
