version: '3'
services:
  elm:
    build: ./elm
    volumes:
      - ./config/elm-package.json:/app/elm-package.json
      - ../src:/app/src
      - ../out:/app/out
      - cache1:/app/elm-stuff

  elm-doc:
    build: ./elm-doc
    volumes:
      - ./config/elm-package.json:/app/elm-package.json
      - ../src:/app/src
      - cache2:/app/docs
      - ../docs/api:/app/api

volumes:
  cache1: # 名前付きボリューム名
  cache2: