
- name: check minikube version
  shell: minikube version 
  register: ver_check
  ignore_errors: True
  check_mode: no
  failed_when: no
  changed_when: ver_check.rc != 0

- name: debug minikube version
  debug: var=ver_check

# - name: if not install minikube then install
#   shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
#   when: ver_check.rc != 0
#   ignore_errors: True
- name: if not install minikube then install
  script: install.sh
  when: ver_check.rc != 0

# - name: check kubectl version
#   shell: kubectl version 
#   register: ver_check
#   ignore_errors: True
#   check_mode: no
#   failed_when: no
#   changed_when: ver_check.rc != 0

# - name: debug kubectl version
#   debug: var=ver_check

# - name: if not install kubectl then install
#   shell: snap install kubectl --classic
#   when: ver_check.rc != 0