
logstash:
  image: logstash:5.0
#  volumes:
#    - ./logstash.conf:/etc/logstash.conf
  links:
    - elasticsearch
  command: -f /etc/logstash.conf

elasticsearch:
  image: elasticsearch:5.0
#  volumes:
#    - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml

kibana:
  image: kibana:5.0
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
