version: '2'
services:
  wmfw:
    build: ./express
    environment: 

    # log4j用設定ファイルの場所
    - LOG4JS_CONFIG=/wmfw/wmfwapp/config/log4js.json

    # 標準時刻を日本に設定
    - TZ=Asia/Tokyo
    volumes:

    # サーバ設定
    - ./express/package.json:/wmfw/wmfwapp/package.json
    - ./express/.babelrc:/wmfw/wmfwapp/.babelrc

    # ログ格納
    - ./dist/logs:/wmfw/dist/logs

    # アプリケーション設定
    - ./myproject/src/server/app.js:/wmfw/wmfwapp/app.js
    - ./myproject/src/server/server.js:/wmfw/wmfwapp/server.js

    # アプリケーションソース
    - ./myproject/src/server/bin:/wmfw/wmfwapp/bin
    - ./myproject/src/server/config:/wmfw/wmfwapp/config
    - ./myproject/src/server/routes:/wmfw/wmfwapp/routes
    - ./myproject/src/server/controllers:/wmfw/wmfwapp/controllers
    - ./myproject/src/server/models:/wmfw/wmfwapp/models

    # mvc
    - ./myproject/src/client/views:/wmfw/wmfwapp/views

    # 静的ファイル
    - ./myproject/src/server/public/favicon.ico:/wmfw/wmfwapp/public/favicon.ico
    - ./myproject/src/client/css:/wmfw/wmfwapp/public/css

    # データベースファイル
    - ./dist/db:/wmfw/dist/db

    # データベースマイグレーション用ディレクトリ
    - ./myproject/src/server/data/migrations:/wmfw/wmfwapp/migrations
    - ./myproject/src/server/data/seeders:/wmfw/wmfwapp/seeders
    - ./myproject/src/server/data/db:/wmfw/wmfwapp/data/db

    #  - ./myapp/public:/my_express/myapp/public
    #  - ./myapp/views:/my_express/myapp/views
    #  - ./myapp/routes:/my_express/myapp/routes
    ports:
      - "3000:3000"
    command: [npm, run, start]