version: '2'
services:
  wmfw:
    build: ./express
    volumes:
    - ./project/src/wmfwapp/package.json:/wmfw/wmfwapp/package.json
    - ./project/src/wmfwapp/bin:/wmfw/wmfwapp/bin
    - ./project/src/wmfwapp/app.js:/wmfw/wmfwapp/app.js
    #  - ./myapp/public:/my_express/myapp/public
    #  - ./myapp/views:/my_express/myapp/views
    #  - ./myapp/routes:/my_express/myapp/routes
    ports:
      - "3000:3000"
    command: [node, bin/www]