# ansibleインストール用shell
$ansible_install = <<SHELL
  if ! type virtualenv > /dev/null 2>&1; then
    # rootユーザとして実行されるためsudo不要
    sudo apt-get update
    sudo apt-get -y install curl
    sudo apt-get -y install libffi-dev libssl-dev python-pip
    sudo pip install --upgrade pip
    sudo pip install virtualenv

    # vagrantユーザとしてvirtualenvとansibleをインストール
    su -c "source /vagrant/provision/bash/install_ansible.sh" vagrant
  fi
SHELL

# virtual machine設定
Vagrant.configure(2) do |config|
  # 使用するディストリビューションのボックスの設定
  config.vm.box = "bento/ubuntu-18.04"

  # ネットワーク設定。
  config.vm.network "private_network", ip: "192.168.50.100"

  config.vm.provider "virtualbox" do |vm|
    # メモリを設定
    vm.memory = 2048
    # Vagrant1.8から利用出来るLinked Cloneをオンにする。
    vm.linked_clone = true
  end
  
  # ansibleをインストール
  config.vm.provision "shell", inline: $ansible_install
  # ansibleを実行
  config.vm.provision "shell", inline: <<-SHELL
    # timezoneを日本に変更
    timedatectl set-timezone Asia/Tokyo
    # virtualenv起動
    source /home/vagrant/venv/bin/activate
    # provision 実行
    # 失敗した場合は vagrant up後に vagrant provision
    # それでも失敗した場合は、windows再起動後にもう一度vagrant up vagrant provision
    ANSIBLE_CONFIG=/vagrant/provision/.ansible.cfg ansible-playbook -i /vagrant/provision/playbooks/inventory/hosts /vagrant/provision/playbooks/site.yml -c local -v
  SHELL
end
