version: "3"
services:
  # サーバー

  # php
  php: 
    build: ./server/apache
    environment:
      # replace with your local IP
      XDEBUG_CONFIG: remote_host=192.168.15.8
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/apache2
    ports: 
      - "80:80"

  # データベースへアクセス
  adminer:
    image: adminer
    ports: 
      - "8080:8080"

 # データボリュームコンテナ
  sqldata:
    image: busybox
    volumes:
      - dbdata:/var/lib/mysql

  # データベース
  db:
    build: ./server/mysql
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro # 時刻の同期
      - ./server/mysql/init:/docker-entrypoint-initdb.d # 初期実行
      - ./data:/data
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"

volumes:
  dbdata: # 名前付きボリューム名




