FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y nginx-extras
RUN apt-get install -y fcgiwrap
RUN apt-get install -y software-properties-common python-software-properties
RUN apt-add-repository -y ppa:brightbox/ruby-ng
RUN apt-get update
RUN apt-get install -y ruby2.4 
RUN apt-get install -y ruby-uconv  
RUN apt-get install -y libfcgi-dev
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y ruby2.4-dev
RUN apt-get install -y rake
RUN apt-get install -y gem2.4
RUN apt-get install -y fcgi
RUN apt-get install -y msgpack
RUN apt-get install -y json
RUN apt-get install -y i18n
