version: '3'
services:
  server:
    image: nginx:1.13.3
    volumes:
      - ./public:/usr/share/nginx/html:ro 
    ports:
      -  80:80

  awscli:
    build: ./aws-cli  
    volumes:
      - ./public:/public
      - ./aws-cli/.aws:/root/.aws
      - ./aws-cli/conf:/conf
  
  jasmine:
    build: ./tools/jasmine
    volumes:
      - ./public:/home/workdir/public
      - ./tools/jasmine/app.js:/home/workdir/app.js
    ports:
      -  3000:3000
    working_dir: /home/workdir
    command: node app.js