version: "3"
services:
  realworld:
    # Dockerfileビルド
    build: ./golang
    # ディレクトリを共有する。
    volumes:
      - ../src:/app/src
      - ../handson:/app/handson
    working_dir: /app
    ports:
      - 18888:18888
