version: '2'
services:
  documentation_generator:
    build: ./documentation_generator
    volumes:
      # sphinxのMakefile
      - ./documentation_generator/sphinx/Makefile:/root/Makefile
      # sphinxの起動ファイル
      - ./documentation_generator/sphinx/build.sh:/root/build.sh
      # shpinxの生成するHTMLのテンプレート
      - ./documentation_generator/sphinx/source/_templates:/root/source/_templates
      # shpinxの静的HTMLファイル
      - ./documentation_generator/sphinx/source/_templates:/root/source/_static
      # sphinxのコンフィグファイル
      - ./documentation_generator/sphinx/source/conf.py:/root/source/conf.py

      # esdocの設定ファイル
      - ./documentation_generator/esdoc/.esdoc.json:/root/.esdoc.json

      # sphinxでコンパイルするときの開始ファイル
      - ./docs/index.rst:/root/source/index.rst
      # ドキュメントのフォルダ
      - ./docs/contents:/root/source/contents
      # ビルドされたファイルの格納ディレクトリ
      - ./dist/docs:/root/build
      # apiドキュメントを作成したいソースファイルの格納ディレクトリ
      - ./src:/root/src


