# server:
#   build: ./express
#   volumes:
#    - ./myapp/views:/my_express/myapp/views
#    - ./dist:/my_express/myapp/public/javascripts
#   ports:
#     - "80:3000"
#   command: [node, bin/www]

buildtool:
  build: ./webpack
  volumes:
   - ./src:/my_webpack/src
   - ./dist:/my_webpack/dist
   - ./webpack/package.json:/my_webpack/package.json
   - ./webpack/webpack.config.babel.js:/my_webpack/webpack.config.babel.js
   - ./webpack/.babelrc:/my_webpack/.babelrc
  ports:
    - "8080:8080"
  command: [npm, run, start]
  # command: [npm, run, build]