# http://dev.classmethod.jp/tool/docker/apline-accelerates-docker-dev/
FROM alpine:edge

# http://qiita.com/dd511805/items/dfe03c5486bf1421875a
RUN apk add --update \
        udev \
        ttf-freefont \
        chromium

# ENTRYPOINT tail -f /dev/null