version: '3'
services:
  # htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../src/templates:/app/src
      - ../dist/html:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  webpacks:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../dist:/app/dist
      - ../product:/app/product
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
      - ../config/.eslintrc:/app/.eslintrc
      - ../config/.esdoc.json:/app/.esdoc.json
      - ../config/tsconfig.json:/app/tsconfig.json
      - ../config/tslint.json:/app/tslint.json
      - ../config/.stylelintrc:/app/.stylelintrc
      - ../config/elm.json:/app/elm.json
      - ../config/webpack.config.js:/app/webpack.config.js
