version: '3'
services:
  webpack:
    build: ./webpack
    volumes:
      - ../src:/app/src
      - ../app:/app/dist
      - ../product:/app/product
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
      - ../config/.eslintrc:/app/.eslintrc
      - ../config/.esdoc.json:/app/.esdoc.json
      - ../config/tsconfig.json:/app/tsconfig.json
      - ../config/tslint.json:/app/tslint.json
      - ../config/.stylelintrc:/app/.stylelintrc
      - ../config/postcss.config.js:/app/postcss.config.js
      - ../config/elm.json:/app/elm.json
      - ../config/.babelrc:/app/.babelrc
      - ../config/webpack.config.babel.js:/app/webpack.config.babel.js
      - ../config/webpack:/app/webpack
    ports:
      - 8080:8080
    command: [yarn, run, webpack-dev-server, --mode, development]