version: '3'
services:
  # htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../src/templates:/app/src
      - ../dist/html:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  webpacks:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../dist:/app/dist
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
