version: '2'
services:
  wmfw_sphinx:
    build: .
    volumes:
      - ./Makefile:/root/Makefile
      # ビルドするソースファイル
      - ../../project/src:/root/src
      # ビルドするドキュメントファイル
      - ./source:/root/source
      # ビルドされた結果ファイル
      - ../../dist/docs:/root/build
      # - ../../docs:/root/docs
      # コンテナ上のpackage.jsonを上書き
      # - ./package.json:/my_jsdoc/package.json