version: '3'
services:
  database:
    build:
      context: ./oracle/11.2.0.2/
      dockerfile: Dockerfile.xe
    env_file: .env
    volumes:
      - ./data:/u01/app/oracle/oradata
    ports:
      - 1521:1521
      - 8085:8080
    shm_size: 1g
    restart: unless-stopped
  gradle:
    build: ./gradle
    volumes:
      - ../src/hello:/app
    command: [echo, "no work"]
  spring:
    build: ./spring
    ports:
        - "8080:8080"
    volumes:
        - ../src/hello:/app
    command: [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app/build/libs/hello-0.0.1-SNAPSHOT.jar"]
