---
# docker 
# Installation ubuntu 
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
  
  - name: dockerがインストールされていなければインストール
    command: docker
    register: result
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: result.rc != 0
  
  - block:
    - name: step0.5
      shell: echo 127.0.1.1 $(hostname) >> /etc/hosts

# http://qiita.com/udzura/items/576c2c782adb241070bc
# https://gist.github.com/indykish/a6facea4748dc578abbaf2b09065ead5
    - name: step1
      shell: export DEBIAN_FRONTEND=noninteractive

# 一部環境では以下を実行しないとエラーが発生
# aptが起動していて次のタスクが立ち上がらないエラー
    - name: step1.5
      shell: killall -KILL apt.systemd.daily
      ignore_errors: True

    - name: step2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apt-transport-https 
        - ca-certificates 
        - curl
        - software-properties-common

    - name: step3.1
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      register: res3
      ignore_errors: True

    - name: step4
      shell: apt-key fingerprint 0EBFCD88 warn=no

    - name: step5.1
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" warn=no

    - name: step5.2
      shell: apt-get update warn=no

    - name: step6
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - docker-ce

    - name: step6.2
      shell: apt-cache madison docker-ce warn=no

    - name: step8
      shell: gpasswd -a vagrant docker
    when: result|failed
  
  - name: test docker-composeが インストールされていなければインストール
    command: docker-compose --version
    register: result
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: result.rc != 0
  
  - block:
    - name: step1
      shell: curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose &&  chmod +x /usr/local/bin/docker-compose warn=no

    when: result|failed