---
- name: docker-composeとdockerを同時にインストール
  apt: pkg=docker-compose

- name: そのままだとsudoが必要なのでグループにdockerを追加
  user:
    name: vagrant
    groups: vagrant,docker

- name: "プロキシ設定の修正(1)"
  lineinfile: >-
    dest='/etc/resolv.conf'
    state=present
    backrefs=yes
    regexp='^nameserver'
    line='nameserver 8.8.8.8'
