---
# docker 
# Installation ubuntu 
# https://docs.docker.com/engine/installation/linux/ubuntulinux/

- block:
  - name: dockerがインストールされていればバージョンを確認
    shell: docker --version | grep {{ docker_version }}
    register: ver_check
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: ver_check.rc != 0

  - name: debug docker version
    debug: var=ver_check

  - name: バージョンがvarsで指定されたものと異なれば、Remove "docker" package
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - docker-ce
        - docker 
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
    when: ver_check.rc != 0
    ignore_errors: True

  - name: dockerがインストールされていなければインストール
    command: docker
    register: result
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: result.rc != 0

- block:
  - name: debug dockerインストール
    debug: var=result

  - name: install yum-utils
    yum: name=yum-utils state=present

  - name: add docker repo
    shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    args:
      chdir: "/etc/yum.repos.d"
      creates: docker-ce.repo

  - name: install docker-ce
    yum: name=docker-ce state=present

  - name: add group
    user: name=vagrant groups=docker append=yes
    tags: dockerhost
    become: True

  - name: restart docker
    systemd:
      name: docker.service
      state: restarted
      daemon_reload: yes
      enabled: yes
  when: result.rc != 0

- block:
  - name: docker-composeがインストールされていればバージョンを確認
    shell: /usr/local/bin/docker-compose --version | grep {{ docker_compose_version }}
    register: ver_check_compose
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: ver_check_compose.rc != 0

  - name: debug docker-compose
    debug: var=ver_check_compose

  - name: バージョンがvarsで指定されたものと異なれば、Remove "docker-compose" package
    shell: rm /usr/local/bin/docker-compose
    ignore_errors: True
    when: ver_check_compose.rc != 0

  - name: check docker-compose
    command: /usr/local/bin/docker-compose -v
    register: result_compose
    ignore_errors: True
    check_mode: no
    failed_when: no
    changed_when: result_compose.rc != 0

  - name: debug docker-compose
    debug: var=result_compose

# 現在のバージョンに合わせてURLを変えること
- block:
  - name: debug docker-compose result
    debug: var=result_compose
  - name: step1 install docker-compose
    shell: curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose &&  chmod +x /usr/local/bin/docker-compose warn=no
  when: result_compose.rc != 0
  