---

#  バーチャルホスト設定の配備(redmine)
- name: configure/ setup redmine configuration file
  template:
    src: redmine.conf.j2
    dest: /etc/nginx/conf.d/redmine.conf
    owner: root
    group: root
    mode: 0644