---
- name: install versions for each user
  shell: bash -lc "nvm install {{ item.1 }}"
  become: true
  become_user: "{{ item.0 }}"
  with_nested:
    - "{{ nvm_users }}"
    - "{{ nvm_node_versions }}"
  register: output
  changed_when: "'already installed.' not in output.stderr"

- name: create alias directory for each user
  file: path="{{ nvm_root }}/alias" state=directory
  become: true
  become_user: "{{ item }}"
  with_items: "{{ nvm_users }}"

- name: set {{ nvm_default_node_version }} as default version for each user
  copy: dest="{{ nvm_root }}/alias/default" content="{{ nvm_default_node_version }}"
  become: true
  become_user: "{{ item }}"
  with_items: "{{ nvm_users }}"