#
# site.yml
#
- hosts: localhost
  become: yes # 
  become_user: root # 以下、sudoコマンドが不要になる 
  roles:
    - common
    - git
    - docker
    - ssh
    # - minikube#
    # - node
    # - vim
    # - aws