#
# site.yml
#
- hosts: localhost
  become: yes #
  become_user: root # 以下、sudoコマンドが不要になる
  roles:
    - common
    - docker
    # - git ... 2.25.1がデフォルト
    # - ssh ... デフォルトで入っている
    # - minikube#
    - node
    # - vim
    - aws_sam_cli
    - awscli
