version: '3'
services:

  elm:
    build: ./elm-webpack-starter
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../dist/assets:/app/dist
      - ./config/elm.json:/app/elm.json
      - ./config/webpack.config.js:/app/webpack.config.js
      - ./config/.babelrc:/app/.babelrc
      - ./config/.eslintrc:/app/.eslintrc
      - ./config/.eslintignore:/app/.eslintignore
      - ./config/.stylelintrc:/app/.stylelintrc
      - ./config/tsconfig.json:/app/tsconfig.json
      - ./config/tslint.json:/app/tslint.json
      # packageのキャッシュ
      - cacheElmStuffStarter:/app/elm-stuff
      - cacheDotElmStarter:/root/.elm
      # 分割して出力してみる
      - ../separate/pre-pre-dist:/app/separate/pre-pre-dist
      - ../separate/pre-dist:/app/separate/pre-dist
      - ../separate/dist:/app/separate/dist
      - ./config/postcss.config.js:/app/postcss.config.js
      - ./config/babel.config.js:/app/babel.config.js
      - ./config/webpack.config.separate.js:/app/webpack.config.separate.js
    environment:
      - SHELL=/bin/bash
    ports:
      - 3000:3000
      - 3002:3002
    environment:
      - NODE_ENV=develop
    command: [yarn, webpack-dev-server, --hot, --colors, --port, '3000', --host, '0.0.0.0', ]
      # command: [yarn, run, elm-watch]


volumes:
  # elmのpackageを毎回ダウンロードしなくてもよいように、キャッシュを行う。2か所のキャッシュが必要。
  cacheElmStuffStarter: 
  cacheDotElmStarter:


