---
# - name: install python-pip
#   apt:
#     name: "{{ item }}"
#     state: present
#   with_items: 
#     - python-pip
# この書き方だと仮想環境にインストールされる
# # expectモジュールのインストール
# - name: install pexpect
#   pip: 
#     name: pexpect
# この書き方でも仮想環境にインストールされる
# - name: install pexpect
#   command: pip install pexpect