version: '2'
services:
  wmfw_eslint:
    build: .
    volumes:
      # ビルドするソースファイル
      - ../../project/src:/my_lint/src
      # eslint設定ファイル
      - ./.eslintrc.json:/my_lint/.eslintrc.json
      # コンテナ上のpackage.jsonを上書き
      - ./package.json:/my_lint/package.json