---
## 1. SELinuxのモード変更
- name: configure/ Selinux premissived
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux.config_mode == 'enforcing'

# 2. ipv6インタフェース無効化
- name: configure/ desable ipv6 interface
  sysctl:
    state: present
    name: "{{item}}"
    value: 1
    sysctl_set: yes
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

# 3. yumパッケージアップデート
- name: configure / update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

# 4. epel リポジトリ設定
- name: configure/ import EPEL Repository
  yum: 
    name: epel-release
    state: latest
    update_cache: yes
    