version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 15900:5900
    depends_on:
      - hub
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_ENV_no_proxy=localhost
  node:
    build: ./nodejs
    volumes:
      - ./src:/home/selenium/src
      - /dev/shm:/dev/shm
  chromium:
    build: ./chromium
    volumes:
      - /dev/shm:/dev/shm
  alpine:
    build: ./alpine
    links:
      - hub
      - chrome
    volumes:
      - ./src:/home/selenium/src