version: '3'
services:
  babel:
    build: ./babel
    volumes:
      - ../scripts:/app/scripts

  # ソースコードプロトタイピング
  s2s:
    build: ./s2s
    volumes:
      - ./config/s2s/s2s.config.js:/app/s2s.config.js
      - ../src:/app/src
    command: [yarn, run, s2s]

  # ビルドツール
  webpack:
    build: ./webpack
    volumes:
      - ./config/webpack/.babelrc:/app/.babelrc
      - ./config/webpack/tsconfig.json:/app/tsconfig.json
      - ./config/webpack/tslint.json:/app/tslint.json
      - ./config/webpack.config.babel.js:/app/webpack.config.babel.js
      - ../src:/app/src
      - ../packages:/app/dist
