version: '3'
services:
  # node.js
  node:
    image: node:latest
    working_dir: /home/workdir
    volumes:
      - ./src:/home/workdir/src
      - ./public:/home/workdir/public
  
  # React開発サーバ
  react-app:
    build: ./server/react-app
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/home/workdir/app/src
      - ./app/public:/home/workdir/app/public
      - ./app/package.json:/home/workdir/app/package.json
      - ./build:/home/workdir/app/build
    working_dir: /home/workdir/app
    # Docker用にpollingの設定。ファイルを書き換えた時のブラウザ自動更新を有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # React雛形取り出し
  create-react-app:
    build: ./server/react-app
    container_name: create-react-app
  
  # ビルド結果確認用サーバー
  serve:
    build: ./server/serve
    ports:
      - 3001:3001
    volumes:
      - ./build:/home/workdir/build
    command: serve -s /home/workdir/build -p 3001