version: '3'
services:
  # node.js
  node:
    image: node:latest
    working_dir: /home/workdir
    volumes:
      - ./src:/home/workdir/src
      - ./public:/home/workdir/public
    
  # 構文チェックツール
  lint:
    build: ./tools/lint
    volumes: 
      - ./src:/home/workdir/src
  # トランスパイラ
  babel:
    build: ./tools/babel
    volumes: 
      - ./src:/home/workdir/src
      - ./dist:/home/workdir/dist 
