version: '3'
services:
  # node.js
  node:
    image: node:latest
    working_dir: /home/workdir
    volumes:
      - ./src:/home/workdir/src
      - ./public:/home/workdir/public
  
  # React雛形
  react-app:
    build: ./server/react-app
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/home/workdir/app/src
      - ./app/public:/home/workdir/app/public
      - ./app/package.json:/home/workdir/app/package.json
    working_dir: /home/workdir/app
    command: npm start