version: '3'
services:
  
  # 構文チェックツール
  lint:
    build: ./tools/lint
    volumes: 
      - ./src:/home/workdir/src
  
  # node.js
  node:
    image: node:latest
    working_dir: /home/workdir
    volumes:
      - ./src:/home/workdir/src
      - ./public:/home/workdir/public