---
# - name: Pull docker
#   docker_image:
#     name: mcr.microsoft.com/mssql/rhel/server:2019-CTP2.4
#     source: pull
- name: Deploy Container
  docker_container:
    name: "{{docker_name}}"
    image: "{{docker_image}}"
    pull: true
    restart_policy: always
    state: started
    ports: "{{docker_ports}}"