FROM node:8.6.0

WORKDIR /app

RUN npm init -y

RUN npm i -S express

RUN npm i -D babel-jest 
RUN npm i -D babel-polyfill 
RUN npm i -D babel-preset-es2015 
RUN npm i -D jest

RUN npm i -D typescript
RUN npm i -D ts-jest 
RUN npm i -D @types/jest

# jsViewライブラリmithril
RUN npm i -S mithril

# 
RUN npm i -D tidy-html5
RUN npm i -D mithril-jest
