version: "3.8"
services:
  az-tool:
    build: ./tools
    # volumes:
    #   - ../HttpExample:/app/HttpExample
    # ports:
    #   - 9229:9229
    #   - 7071:7071
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。
    working_dir: /app

  az-functions:
    # Dockerfileビルド
    build: ./functions
    # ディレクトリを共有する。
    volumes:
      - ../HttpExample:/app/HttpExample
      - ../tsconfig.json:/app/tsconfig.json
      - ../local.settings.json:/app/local.settings.json

    ports:
      - 9229:9229
      - 7071:7071
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。
    working_dir: /app
    # command: [vercel, dev]
    command: [npm, run, start]
