version: '3'
services:
  web_components_react:
    build: ./react
    ports:
      - 8080:8080
    volumes:
      - ../src:/app/src
      - ./react/webpack.config.js:/app/webpack.config.js
      - ../../server/src/index.html:/index.html
      - ../../server/dist:/dist
    command: [yarn, start ]