version: '3'
services:
  elm:
    build: ./elm
    volumes:
      - cache1:/app/elm-stuff
      - cache2:/app/tests/elm-stuff
    ports:
      - 3000:3000
    command: [yarn, repl]

volumes:
  cache1: # 名前付きボリューム名
  cache2: