version: '3'
services:
  # htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../src/templates:/app/src
      - ../dist/html:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  ts:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../docs:/app/docs
      - ../pre-dist:/app/dist
      # 設定ファイル
      - ../config/tsconfig.json:/app/tsconfig.json
      - ../config/tslint.json:/app/tslint.json

  elm:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../pre-dist:/app/dist
      - ../config/elm.json:/app/elm.json

  js:
    build: ./webpacks
    volumes:
      - ../pre-dist:/app/src
      - ../dist:/app/dist
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
      - ../config/.eslintrc:/app/.eslintrc
      - ../config/.esdoc.json:/app/.esdoc.json

  scss:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../pre-dist:/app/dist
      # 設定ファイル
      - ../config/.stylelintrc:/app/.stylelintrc

  postcss:
    build: ./webpacks
    volumes:
      - ../pre-dist:/app/src
      - ../dist:/app/dist
