version: '3'
services:
  # htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../src/templates:/app/src
      - ../dist/html:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  ts:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../docs:/app/docs
      - ../pre-dist:/app/dist
      # 設定ファイル
      - ../config/tsconfig.json:/app/tsconfig.json
      - ../config/tslint.json:/app/tslint.json
    command: [yarn, run, tsc, --watch]

  elm:
    build: ./elm
    volumes:
      - ../src:/app/src
      - ../pre-dist/assets:/app/dist
      - ../config/elm.json:/app/elm.json
      # packageのキャッシュ
      - cacheElmStuff:/app/elm-stuff
      - cacheDotElm:/root/.elm
    environment:
      - SHELL=/bin/bash
    command: [yarn, run, elm-watch]

  js:
    build: ./webpacks
    volumes:
      - ../pre-dist:/app/src
      - ../dist:/app/dist
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
      - ../config/.eslintrc:/app/.eslintrc
      - ../config/.esdoc.json:/app/.esdoc.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: [yarn, run, babel, src, --out-dir, /app/dist, --watch]

  scss:
    build: ./webpacks
    volumes:
      - ../src:/app/src
      - ../pre-dist:/app/dist
      - ../config/.stylelintrc:/app/.stylelintrc
    command: [yarn, run, node-sass, -r, /app/src/assets/css, -o, /app/dist/assets/css, --watch]

  postcss:
    build: ./webpacks
    volumes:
      - ../pre-dist:/app/src
      - ../dist:/app/dist
      - ../config/postcss.config.js:/app/postcss.config.js
    command: [yarn, run, postcss, /app/src/assets/css/*.css, --no-map, --dir, /app/dist/assets/css/, --watch]

  webpack:
    build: ./webpacks
    volumes:
      - ../dist:/app/src
      - ../app/public:/app/dist
      # 設定ファイル
      - ../config/babel.config.js:/app/babel.config.js
      - ../config/webpack.config.js:/app/webpack.config.js
    environment:
      - NODE_ENV=develop
    ports:
      - 8080:8080
    command: [yarn, run, webpack-dev-server, --hot]

volumes:
  # elmのpackageを毎回ダウンロードしなくてもよいように、キャッシュを行う。2か所のキャッシュが必要。
  cacheElmStuff: 
  cacheDotElm:

