version: '3'
services:
  babel:
    build: ./babel
    volumes:
      - ../packages:/app/packages

  # ソースコードプロトタイピング
  s2s:
    build: ./s2s
    volumes:
      - ./config/s2s/s2s.config.js:/app/s2s.config.js
      - ./config/s2s/templates:/app/templates
      - ../packages/babel-plugin-s2s-redux-actions-root-ts:/app/babel-plugin-s2s-redux-actions-root-ts
      - ../packages/s2s-utils-ts:/app/s2s-utils-ts
      - ../test/src:/app/src
    command: [yarn, run, s2s]

  # ビルドツール
  ts:
    build: ./ts
    volumes:
      - ./config/ts/.babelrc:/app/.babelrc
      - ./config/ts/tsconfig.json:/app/tsconfig.json
      - ./config/ts/tslint.json:/app/tslint.json
      - ./config/ts/jest.config.js:/app/jest.config.js
      - ./config/ts/webpack.config.babel.js:/app/webpack.config.babel.js
      - ../src:/app/src
      - ../packages:/app/dist
