proxy:
  image: identiproxy:0.1
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.50.10
    - NGINX_PROXY=http://identidock:9090
identidock:
  image: identidock:1.0
  links:
   - dnmonster
   - redis
  environment:
    ENV: PROD
dnmonster:
  image: amouat/dnmonster
redis:
  image: redis

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOT: ignore
  links:
    - elasticsearch
  ports:
    - "5544:5544"
  command: -f /etc/logstash.conf


elasticsearch:
  image: elasticsearch:1.7
  environment:
    LOGSPOUT: ignore

kibana:
  image: kibana:4.1
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
