FROM node:7.1.0
WORKDIR /my_webpack_react
RUN npm init -y
RUN npm install --save react
RUN npm install --save react-dom
RUN npm install --save-dev webpack
RUN npm install --save-dev babel-loader 
RUN npm install --save-dev babel-core
RUN npm install --save-dev babel-preset-react
RUN npm install --save-dev babel-preset-es2015