---
- include_vars: roles/redmine/vars/secret.yml
- block:
#### block 開始 ####
  # 2. redmine データベース作成
  - name: configure / create redmine database
    mysql_db:
      login_password: "{{ mysql_root_password }}"
      name: "{{ redmine_db_name }}"
      state: present

  # 3. redmineユーザ作成
  - name: configure / create redmine database user
    mysql_user:
      login_password: "{{ mysql_root_password }}"
      name: "{{ redmine_db_user }}"
      password: "{{ redmine_db_password }}"
      host: "%"
      priv: "{{ redmine_db_name }}.*:ALL"
      state: present

  run_once: true
#### block 終了 ####