---
# 1. mysqlインストール前の事前タスクの呼び出し
- include: roles/mysql/tasks/check_install.yml
# 2. mysql インストール
- include: roles/mysql/tasks/install.yml
# 3. mysql 初期設定
- include: roles/mysql/tasks/configure.yml
# 4. wordpress設定
- include: roles/mysql/tasks/create_wordpress_user.yml
