version: '3'
services:
  node:
    build: "."
    volumes:
      - ./dist:/dist
      - ./bin/build_bundle.sh:/home/node/build_bundle.sh
      - ./sspa:/home/node/sspa
    command: /home/node/build_bundle.sh