---
nginx_service_ip: "{{ hostvars.webs1.ansible_host }}"
nginx_service_port: 80
nginx_firewalld_port:
  - "{{ nginx_service_port }}/tcp"

http_doc_root: "/usr/share/nginx/html"

nginx_packages:
  - nginx
  - MySQL-python