version: '3'
services:

  # awsへの接続
  awscli:
    build: ./aws-cli  
    volumes:
      - ../../dist/deploy:/public
      - ./aws-cli/.aws:/root/.aws
      - ./aws-cli/conf:/conf
  # markdown to html
  pandoc:
    build: ./pandoc
    working_dir: /home/workdir/docs
    volumes:
      - ../../../docs:/home/workdir/docs
      - ../../dist/pandoc:/home/workdir/dist
  