---

ansible_ssh_pass: 'some password'

ansible_sudo_pass: 'some password'

# The password for the sa user. Only used if mssql-server needs to be installed.
sa_password: 'some password'

# The password for the master key
master_key_password: 'some password'

# The SQL password for the DBM endpoint user
dbm_password: 'some password'

# The password for the DBM cert private key
dbm_cert_password: 'some password'

# The password of the user that admins the pacemaker cluster (hacluster)
pacemaker_cluster_password: 'some password'

# The SQL password for the pacemaker user
pacemaker_password: 'some password'