version: '3'
services:
  web_components:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../dist:/usr/share/nginx/html/dist
      - ../src/index.html:/usr/share/nginx/html/index.html
