---

# install mssql-server package

- name: install mssql-server repo (CentOS, RedHat)
  get_url:
    url: "{{ centos_server_repo_url }}"
    dest: /etc/yum.repos.d/mssql-server.repo
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: install mssql-server repo (Ubuntu)
  get_url:
    url: "{{ ubuntu_server_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-server.list
  when: ansible_distribution == 'Ubuntu'

- name: refresh apt-get cache for server repo (Ubuntu)
  command: apt-get update
  when: ansible_distribution == 'Ubuntu'

- name: install mssql-server package
  package:
    name: mssql-server
    state: latest


# setup

- name: mssql-server setup
  mssql_conf:
    setup_sa_password: "{{ sa_password }}"
    setup_pid: "{{ pid }}"
    login_name: 'sa'
    login_password: "{{ sa_password }}"


# TSQL endpoint

- name: set TSQL endpoint port
  mssql_conf:
    name: network.tcpport
    value: "{{ tsql_endpoint_port }}"
    login_name: 'sa'
    login_password: "{{ sa_password }}"

- name: check if firewalld is installed (CentOS, RedHat)
  command: rpm -q firewalld
  register: firewalld_installed
  failed_when: false
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: open TSQL endpoint in firewall (CentOS, RedHat)
  firewalld:
    port: "{{ tsql_endpoint_port }}/tcp"
    state: enabled
    permanent: true
  when: (ansible_distribution in ['CentOS', 'RedHat']) and firewalld_installed.rc == 0


- name: reload firewall (CentOS, RedHat)
  command: firewall-cmd --reload
  # vagrantでは"FirewallD is not running"と言われて失敗する
  failed_when: false
  when: (ansible_distribution in ['CentOS', 'RedHat']) and firewalld_installed.rc == 0

- name: open TSQL endpoint in firewall (Ubuntu)
  ufw:
    port: "{{ tsql_endpoint_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'


# mssql-tools package

- name: install mssql-tools repo (CentOS, RedHat)
  get_url:
    url: "{{ centos_tools_repo_url }}"
    dest: /etc/yum.repos.d/mssql-tools.repo
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: install mssql-tools repo (Ubuntu)
  get_url:
    url: "{{ ubuntu_tools_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-tools.list
  when: ansible_distribution == 'Ubuntu'

- name: refresh apt-get cache for tools repo (Ubuntu)
  command: apt-get update
  when: ansible_distribution == 'Ubuntu'

- name: install mssql-tools package
  package:
    name: mssql-tools
    state: latest
  environment:
    ACCEPT_EULA: 'y'


# Start mssql-server service

- name: start sqlservr
  service:
    name: mssql-server
    state: started

# テスト用のユーザ作成
- name: add user
  mssql_login:
    name: "{{ test_user_name }}"
    password: "{{ test_user_pass }}"
    roles:
    # DBの追加・削除ができる権限
      - dbcreator
    login_name: 'sa'
    login_password: "{{ sa_password }}"

- name: パスを通す 接続したとき
  lineinfile:
    path: /home/vagrant/.bash_profile
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'

- name: パスを通す 各bashごと毎回
  lineinfile:
    path: /home/vagrant/.bash_profile
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'

- name: 初期DBの作成。大文字小文字を区別する設定に変更
  shell: /opt/mssql-tools/bin/sqlcmd -S localhost -U test_db_user -P '!test_password001' -Q "IF DB_ID (N'TestDB') IS NULL create database [TestDB] collate Japanese_CS_AS"
  register: result
  changed_when: result.rc != 0

- name: 初期テーブルの作成。
  shell: /opt/mssql-tools/bin/sqlcmd -S localhost -U test_db_user -P '!test_password001' -d TestDB -Q "if object_id('TestTable') is null CREATE TABLE TestTable (id INT IDENTITY(1,1) NOT NULL,name NVARCHAR(128), CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED ([id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]"
  register: result
  changed_when: result.rc != 0


- name: 初期データの挿入
  shell: /opt/mssql-tools/bin/sqlcmd -S localhost -U test_db_user -P '!test_password001' -d TestDB -Q "INSERT INTO TestTable(name) SELECT 'ばなな' name WHERE NOT EXISTS (select 1 from TestTable where name = 'ばなな')"
  register: result
  changed_when: result.rc != 0
