Resources:
  kotatestServiceRoleAB0D659B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Cdk20210310Stack/kotatest/ServiceRole/Resource
  kotatest9BC467AF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceS3Bucket1692E596
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceS3VersionKey7AD44C64
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceS3VersionKey7AD44C64
      Role:
        Fn::GetAtt:
          - kotatestServiceRoleAB0D659B
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      FunctionName: kotatest
      Handler: index.handler
      Runtime: nodejs14.x
    DependsOn:
      - kotatestServiceRoleAB0D659B
    Metadata:
      aws:cdk:path: Cdk20210310Stack/kotatest/Resource
      aws:asset:path: D:\develop\develop\tutorial\lesson\aws\typescript\projects\cdk_20210310\cdk.out\asset.8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfce
      aws:asset:property: Code
Parameters:
  AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceS3Bucket1692E596:
    Type: String
    Description: S3 bucket for asset "8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfce"
  AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceS3VersionKey7AD44C64:
    Type: String
    Description: S3 key for asset version "8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfce"
  AssetParameters8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfceArtifactHash96DAAD5E:
    Type: String
    Description: Artifact hash for asset "8fe41ff228eb857f9ab5efe9d56314f602e0487530a315a8d3473b86680ecfce"

