version: '3'
services:
  web_components_angular:
    build: ./angular
    ports:
      - 8080:4200
    environment:
      - CHROME_BIN=/usr/bin/google-chrome
    volumes:
      - ./angular/package.json:/app/package.json
      - ./angular/tsconfig.json:/app/tsconfig.json
      - ./angular/tslint.json:/app/tslint.json
      - ./angular/angular.json:/app/angular.json
      - ./angular/.gitignore:/app/.gitignore
      - ../src:/app/src
      - ../e2e:/app/e2e
      - ../../server/src/index.html:/index.html
      - ../../server/dist:/dist
    # コンテナの外からつなぐために 0.0.0.0 のホストを指定。
    # windows ではポーリングが必要
    command: [yarn, start, --host, "0.0.0.0", --poll=2000]