version: '3'
services:

  nodejs:
    build: ./nodejs
    volumes:
      - ../app:/app/app
      - ../src:/app/src
      - ../tests:/app/tests
      - ../dist/assets:/app/dist
      - ./config/.babelrc:/app/.babelrc
      - ./config/.eslintrc:/app/.eslintrc
      - ./config/.eslintignore:/app/.eslintignore
      - ./config/tsconfig.json:/app/tsconfig.json
      - ./config/tslint.json:/app/tslint.json
      # 分割して出力してみる
      - ../separate/pre-pre-dist:/app/separate/pre-pre-dist
      - ../separate/pre-dist:/app/separate/pre-dist
      - ../separate/dist:/app/separate/dist
      - ./config/babel.config.js:/app/babel.config.js
      - ../downloads/wasureta-d6b34.firebaseapp.com:/app/wasureta-d6b34.firebaseapp.com
    command: [node, app/index, https://wasureta-d6b34.firebaseapp.com/index.html]

