version: '3'
services:
  zeit_now:
    # Dockerfileビルド
    build: ./now
    # ディレクトリを共有する。
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../dist:/app/build
      - ../next.config.js:/app/next.config.js
      - ../.now:/app/.now
      - ../.nowignore:/app/.nowignore

    ports:
      - 3000:3000 # ホスト:コンテナでポート指定
    environment:
      - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。
    working_dir:
        /app
    command: [now, dev]
    